# This file provides instructions for packaging.

@prefix : <http://ontologi.es/doap-deps#>.

`Devel-StrictMode`
	:runtime-requirement    [ :on "perl 5.006"^^:CpanId ];
	:test-requirement       [ :on "Test::More 0.47"^^:CpanId ];
	.

